Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
    config.vm.hostname = "myserver"        
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpus",2]
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.gui = false    
    end
  config.vm.boot_timeout = 600
  config.vm.network "forwarded_port", guest:22, host:2021, id:"ssh"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    sudo apt update -y
    sudo apt install -y build-essential linux-headers-$(uname -r) dkms virtualbox-guest-utils    
  SHELL
  config.vm.provision "shell" do |s|
    s.path = "startup_script.sh"
    s.privileged = true
    s.args = []
    s.keep_color = true
  end
  config.vm.provision "shell" do |s|
    s.path = "health_check.sh"
    s.privileged = true
    s.args = []
    s.keep_color = true 
  end  
end